### ISSUE TITLE
ValueError: slice index 1 of dimension 0 out of bounds.

### ISSUE THREAD

**Issue by zsylj** [xyvirtualgroup/MetaSCI-CVPR2021#2]
Traceback (most recent call last):
  File "/home/XXX/MetaSCI/main_MetaTrain_parallel.py", line 90, in <module>
    xtask_output = forward_modulation(mask[i], X_meas_re[i], X_gt[i], weights, weights_m, batch_size, num_frame)
  File "/home/XXX/anaconda3/envs/metasci/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/XXX/anaconda3/envs/metasci/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 1036, in _slice_helper
    return strided_slice(
  File "/home/XXX/anaconda3/envs/metasci/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/home/XXX/anaconda3/envs/metasci/lib/python3.9/site-packages/tensorflow/python/ops/array_ops.py", line 1209, in strided_slice
    op = gen_array_ops.strided_slice(
  File "/home/XXX/anaconda3/envs/metasci/lib/python3.9/site-packages/tensorflow/python/ops/gen_array_ops.py", line 10474, in strided_slice
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/home/XXX/anaconda3/envs/metasci/lib/python3.9/site-packages/tensorflow/python/framework/op_def_library.py", line 748, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/home/XXX/anaconda3/envs/metasci/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3528, in _create_op_internal
    ret = Operation(
  File "/home/XXX/anaconda3/envs/metasci/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 2015, in __init__
    self._c_op = _create_c_op(self._graph, node_def, inputs,
  File "/home/XXX/anaconda3/envs/metasci/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 1856, in _create_c_op
    raise ValueError(str(e))
ValueError: slice index 1 of dimension 0 out of bounds. for '{{node forward_1/strided_slice}} = StridedSlice[Index=DT_INT32, T=DT_FLOAT, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1](Placeholder, forward_1/strided_slice/stack, forward_1/strided_slice/stack_1, forward_1/strided_slice/stack_2)' with input shapes: [1,256,256,8], [1], [1], [1] and with computed input tensors: input[1] = <1>, input[2] = <2>, input[3] = <1>.

**Comment by zsylj** [comment]
looks like the `num_task` variables is the "number of gpus"
and variable `mask` has 4 dimensions `[num_task, image_dim, image_dim, num_frame]`
instead of using `mask[i]`, try `mask[i,:,:,:]`.
